version: '3.0'
services:
  database:
    image: meu-projeto
    container_name: projeto
    environment: 
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: projeto
    ports: 
      - 5432:5432 
