version: '3.0'
services:
  build: 
    dockerfile: ./Dockerfile
    context: '.'
  database:
    image: postgres
    container_name: elefante
    environment: 
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: adelson
      POSTGRES_DB: seila
    ports: 
      - 5000:5432 
