version: '3.0'
services:

  database:
    image: meu-projeto
    container_name: projeto
    environment: 
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: projeto
    ports: 
      - 5432:5432 

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"    
